language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed kmoll/udagram-api-feed:v2
  - docker tag udagram-api-user kmoll/udagram-api-user:v2
  - docker tag udagram-frontend kmoll/udagram-frontend:v6
  - docker tag reverseproxy kmoll/reverseproxy:v2

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  -  docker push kmoll/udagram-api-feed:v1
  -  docker push kmoll/udagram-api-user:v1
  -  docker push kmoll/udagram-frontend:v1
  -  docker push kmoll/reverseproxy:v1